export { splitProps, splitOrDefault } from "./splitProps";
export { numberToRem } from "./numberToRem";
export { setProperties } from "./setProperties";
export { updateWithDefaults } from "./updateWithDefaults";
export { is } from "./is";
export { when } from "./when";
export { trim } from "./trim";
export { isTextTag, createTagChecker } from "./isTextTag";
export { cn } from "./cn";
export { setSlot, setSlots, addSlotProps } from "./slotChange";
export { pipe } from "./pipe";
